<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use AppBundle\Entity\ProductPack;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ProductPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 
class ProductPackRepository extends \Doctrine\ORM\EntityRepository
{
	public function getProductPacksHavingProduct(Product $product)
    {
        $qb = $this->createQueryBuilder('productPack')
        ->where('productPack.product = :product')
        ->setParameter('product', $product)
        ->orderBy('productPack.id', 'ASC');

		return $qb->getQuery()->getResult();
    }
	public function getFirstProductPackHavingProduct(Product $product)
    {
        $qb = $this->createQueryBuilder('productPack')
        ->where('productPack.product = :product')
        ->setParameter('product', $product)
        ->orderBy('productPack.id', 'ASC')
		->setMaxResults(1);

		return $qb->getQuery()->getOneOrNullResult();
    }
}

